name: provision
description: Package to support provisioning (setting the WiFi credentials) of an
  ESP32 through BLE using a PC or an Android app.
environment:
  sdk: ^v2.0.0-alpha.146.5
dependencies:
  protobuf:
    url: github.com/toitware/toit-protobuf
    version: ^1.3.0
