
name: provision
description: Provision ESP32 connect to designated Wi-Fi access point by PC or App of mobile phone.
environment:
  sdk: ^2.0.0-alpha.41
dependencies:
  protobuf:
    url: github.com/toitware/toit-protobuf
    version: ^1.1.0